import { Timestamp } from "firebase/firestore";

interface FlightSchedule {
  flightId: string;
  airplaneCode: string;
  boardingPassId: string;
  departureGate: string;
  boardingTime: Timestamp;
  arrivalTime: Timestamp;
  origin: string;
  destination: string;
  flightStatus: string;
  pilotId: string[];
  cabinCrewId: string[];
}

export const cityData = [
  { code: "NYC", name: "New York City", airport: "JFK Airport" },
  { code: "LAX", name: "Los Angeles", airport: "LAX Airport" },
  { code: "CHI", name: "Chicago", airport: "O'Hare International Airport" },
  {
    code: "SFO",
    name: "San Francisco",
    airport: "San Francisco International Airport",
  },
  {
    code: "DFW",
    name: "Dallas",
    airport: "Dallas/Fort Worth International Airport",
  },
  { code: "MIA", name: "Miami", airport: "Miami International Airport" },
  { code: "LAS", name: "Las Vegas", airport: "McCarran International Airport" },
  { code: "DEN", name: "Denver", airport: "Denver International Airport" },
  {
    code: "SEA",
    name: "Seattle",
    airport: "Seattle-Tacoma International Airport",
  },
  {
    code: "ATL",
    name: "Atlanta",
    airport: "Hartsfield-Jackson Atlanta International Airport",
  },
  {
    code: "HOU",
    name: "Houston",
    airport: "George Bush Intercontinental Airport",
  },
  {
    code: "PHL",
    name: "Philadelphia",
    airport: "Philadelphia International Airport",
  },
  {
    code: "PHX",
    name: "Phoenix",
    airport: "Phoenix Sky Harbor International Airport",
  },
  { code: "BOS", name: "Boston", airport: "Logan International Airport" },
  { code: "MCO", name: "Orlando", airport: "Orlando International Airport" },
  {
    code: "DC",
    name: "Washington, D.C.",
    airport: "Ronald Reagan Washington National Airport",
  },
  {
    code: "MSP",
    name: "Minneapolis",
    airport: "Minneapolis-Saint Paul International Airport",
  },
  { code: "DTW", name: "Detroit", airport: "Detroit Metropolitan Airport" },
  { code: "TPA", name: "Tampa", airport: "Tampa International Airport" },
  {
    code: "FLL",
    name: "Fort Lauderdale",
    airport: "Fort Lauderdale-Hollywood International Airport",
  },
  {
    code: "JFK",
    name: "New York City",
    airport: "John F. Kennedy International Airport",
  },
  {
    code: "SAN",
    name: "San Diego",
    airport: "San Diego International Airport",
  },
  {
    code: "IAD",
    name: "Washington, D.C.",
    airport: "Washington Dulles International Airport",
  },
  {
    code: "SLC",
    name: "Salt Lake City",
    airport: "Salt Lake City International Airport",
  },
  { code: "MDW", name: "Chicago", airport: "Midway International Airport" },
  {
    code: "BWI",
    name: "Baltimore",
    airport: "Baltimore/Washington International Thurgood Marshall Airport",
  },
  {
    code: "STL",
    name: "St. Louis",
    airport: "St. Louis Lambert International Airport",
  },
  { code: "DAL", name: "Dallas", airport: "Dallas Love Field" },
  {
    code: "CLE",
    name: "Cleveland",
    airport: "Cleveland Hopkins International Airport",
  },
  {
    code: "AUS",
    name: "Austin",
    airport: "Austin-Bergstrom International Airport",
  },
  { code: "PDX", name: "Portland", airport: "Portland International Airport" },
  {
    code: "HNL",
    name: "Honolulu",
    airport: "Daniel K. Inouye International Airport",
  },
  {
    code: "IND",
    name: "Indianapolis",
    airport: "Indianapolis International Airport",
  },
  {
    code: "MSY",
    name: "New Orleans",
    airport: "Louis Armstrong New Orleans International Airport",
  },
  {
    code: "CMH",
    name: "Columbus",
    airport: "John Glenn Columbus International Airport",
  },
  {
    code: "RDU",
    name: "Raleigh",
    airport: "Raleigh-Durham International Airport",
  },
  {
    code: "BNA",
    name: "Nashville",
    airport: "Nashville International Airport",
  },
  {
    code: "SMF",
    name: "Sacramento",
    airport: "Sacramento International Airport",
  },
  {
    code: "PIT",
    name: "Pittsburgh",
    airport: "Pittsburgh International Airport",
  },
  {
    code: "SJC",
    name: "San Jose",
    airport: "Norman Y. Mineta San Jose International Airport",
  },
  {
    code: "SAT",
    name: "San Antonio",
    airport: "San Antonio International Airport",
  },
  {
    code: "RSW",
    name: "Fort Myers",
    airport: "Southwest Florida International Airport",
  },
  {
    code: "BUF",
    name: "Buffalo",
    airport: "Buffalo Niagara International Airport",
  },
  { code: "OAK", name: "Oakland", airport: "Oakland International Airport" },
  {
    code: "SJU",
    name: "San Juan",
    airport: "Luis Muñoz Marín International Airport",
  },
  {
    code: "MCI",
    name: "Kansas City",
    airport: "Kansas City International Airport",
  },
  {
    code: "RSW",
    name: "Fort Myers",
    airport: "Southwest Florida International Airport",
  },
  { code: "SNA", name: "Santa Ana", airport: "John Wayne Airport" },
  {
    code: "SDF",
    name: "Louisville",
    airport: "Louisville Muhammad Ali International Airport",
  },
  { code: "OKC", name: "Oklahoma City", airport: "Will Rogers World Airport" },
  { code: "MEM", name: "Memphis", airport: "Memphis International Airport" },
  {
    code: "CVG",
    name: "Cincinnati",
    airport: "Cincinnati/Northern Kentucky International Airport",
  },
  { code: "OMA", name: "Omaha", airport: "Eppley Airfield" },
  {
    code: "MKE",
    name: "Milwaukee",
    airport: "General Mitchell International Airport",
  },
  { code: "RIC", name: "Richmond", airport: "Richmond International Airport" },
  { code: "TUS", name: "Tucson", airport: "Tucson International Airport" },
  {
    code: "ABQ",
    name: "Albuquerque",
    airport: "Albuquerque International Sunport",
  },
  {
    code: "ROC",
    name: "Rochester",
    airport: "Greater Rochester International Airport",
  },
  {
    code: "GRR",
    name: "Grand Rapids",
    airport: "Gerald R. Ford International Airport",
  },
  {
    code: "JAX",
    name: "Jacksonville",
    airport: "Jacksonville International Airport",
  },
  {
    code: "BHM",
    name: "Birmingham",
    airport: "Birmingham-Shuttlesworth International Airport",
  },
  {
    code: "ICT",
    name: "Wichita",
    airport: "Wichita Dwight D. Eisenhower National Airport",
  },
  { code: "DAY", name: "Dayton", airport: "Dayton International Airport" },
  {
    code: "SYR",
    name: "Syracuse",
    airport: "Syracuse Hancock International Airport",
  },
  { code: "ALB", name: "Albany", airport: "Albany International Airport" },
  { code: "PWM", name: "Portland", airport: "Portland International Jetport" },
  {
    code: "GSO",
    name: "Greensboro",
    airport: "Piedmont Triad International Airport",
  },
  { code: "GEG", name: "Spokane", airport: "Spokane International Airport" },
  {
    code: "BTV",
    name: "Burlington",
    airport: "Burlington International Airport",
  },
  { code: "ELP", name: "El Paso", airport: "El Paso International Airport" },
  {
    code: "FAT",
    name: "Fresno",
    airport: "Fresno Yosemite International Airport",
  },
  {
    code: "TLH",
    name: "Tallahassee",
    airport: "Tallahassee International Airport",
  },
  { code: "BOI", name: "Boise", airport: "Boise Airport" },
  { code: "EVV", name: "Evansville", airport: "Evansville Regional Airport" },
  {
    code: "LAN",
    name: "Lansing",
    airport: "Capital Region International Airport",
  },
  {
    code: "AMA",
    name: "Amarillo",
    airport: "Rick Husband Amarillo International Airport",
  },
  { code: "CAE", name: "Columbia", airport: "Columbia Metropolitan Airport" },
  {
    code: "HSV",
    name: "Huntsville",
    airport: "Huntsville International Airport",
  },
  { code: "ISP", name: "Islip", airport: "Long Island MacArthur Airport" },
  {
    code: "LBB",
    name: "Lubbock",
    airport: "Lubbock Preston Smith International Airport",
  },
  { code: "TYS", name: "Knoxville", airport: "McGhee Tyson Airport" },
  {
    code: "SGF",
    name: "Springfield",
    airport: "Springfield-Branson National Airport",
  },
  { code: "EUG", name: "Eugene", airport: "Eugene Airport" },
  {
    code: "GPT",
    name: "Gulfport",
    airport: "Gulfport-Biloxi International Airport",
  },
  { code: "FSD", name: "Sioux Falls", airport: "Sioux Falls Regional Airport" },
  { code: "MSN", name: "Madison", airport: "Dane County Regional Airport" },
  {
    code: "MHT",
    name: "Manchester",
    airport: "Manchester-Boston Regional Airport",
  },
  { code: "IDA", name: "Idaho Falls", airport: "Idaho Falls Regional Airport" },
  {
    code: "PSP",
    name: "Palm Springs",
    airport: "Palm Springs International Airport",
  },
  {
    code: "RST",
    name: "Rochester",
    airport: "Rochester International Airport",
  },
  {
    code: "BZN",
    name: "Bozeman",
    airport: "Bozeman Yellowstone International Airport",
  },
  {
    code: "XNA",
    name: "Bentonville/Fayetteville",
    airport: "Northwest Arkansas Regional Airport",
  },
  {
    code: "PIA",
    name: "Peoria",
    airport: "General Wayne A. Downing Peoria International Airport",
  },
  { code: "RAP", name: "Rapid City", airport: "Rapid City Regional Airport" },
  {
    code: "MFR",
    name: "Medford",
    airport: "Rogue Valley International-Medford Airport",
  },
  {
    code: "FWA",
    name: "Fort Wayne",
    airport: "Fort Wayne International Airport",
  },
  {
    code: "ABE",
    name: "Allentown",
    airport: "Lehigh Valley International Airport",
  },
  { code: "CMX", name: "Hancock", airport: "Houghton County Memorial Airport" },
  { code: "TVC", name: "Traverse City", airport: "Cherry Capital Airport" },
  {
    code: "CHO",
    name: "Charlottesville",
    airport: "Charlottesville-Albemarle Airport",
  },
  { code: "BGR", name: "Bangor", airport: "Bangor International Airport" },
  {
    code: "CPR",
    name: "Casper",
    airport: "Casper/Natrona County International Airport",
  },
  { code: "ITH", name: "Ithaca", airport: "Ithaca Tompkins Regional Airport" },
  {
    code: "JAN",
    name: "Jackson",
    airport: "Jackson-Medgar Wiley Evers International Airport",
  },
  { code: "LSE", name: "La Crosse", airport: "La Crosse Regional Airport" },
  {
    code: "SBN",
    name: "South Bend",
    airport: "South Bend International Airport",
  },
  { code: "ASE", name: "Aspen", airport: "Aspen/Pitkin County Airport" },
  { code: "CWA", name: "Mosinee", airport: "Central Wisconsin Airport" },
  { code: "HLN", name: "Helena", airport: "Helena Regional Airport" },
  { code: "BIS", name: "Bismarck", airport: "Bismarck Municipal Airport" },
  { code: "LNK", name: "Lincoln", airport: "Lincoln Airport" },
  { code: "SGU", name: "St. George", airport: "St. George Regional Airport" },
  { code: "GGG", name: "Longview", airport: "East Texas Regional Airport" },
  { code: "EKO", name: "Elko", airport: "Elko Regional Airport" },
  { code: "CDC", name: "Cedar City", airport: "Cedar City Regional Airport" },
  { code: "ALW", name: "Walla Walla", airport: "Walla Walla Regional Airport" },
  {
    code: "LWS",
    name: "Lewiston",
    airport: "Lewiston-Nez Perce County Airport",
  },
  {
    code: "LBL",
    name: "Liberal",
    airport: "Liberal Mid-America Regional Airport",
  },
  { code: "COD", name: "Cody", airport: "Yellowstone Regional Airport" },
  { code: "HYS", name: "Hays", airport: "Hays Regional Airport" },
  {
    code: "MWA",
    name: "Marion",
    airport: "Williamson County Regional Airport",
  },
  { code: "MMH", name: "Mammoth Lakes", airport: "Mammoth Yosemite Airport" },
  {
    code: "RHI",
    name: "Rhinelander",
    airport: "Rhinelander-Oneida County Airport",
  },
  { code: "EAR", name: "Kearney", airport: "Kearney Regional Airport" },
  { code: "HIB", name: "Hibbing", airport: "Range Regional Airport" },
  { code: "BJI", name: "Bemidji", airport: "Bemidji Regional Airport" },
  {
    code: "CIU",
    name: "Sault Ste. Marie",
    airport: "Chippewa County International Airport",
  },
  { code: "PIR", name: "Pierre", airport: "Pierre Regional Airport" },
  { code: "BRD", name: "Brainerd", airport: "Brainerd Lakes Regional Airport" },
  {
    code: "DIK",
    name: "Dickinson",
    airport: "Dickinson Theodore Roosevelt Regional Airport",
  },
  { code: "MOT", name: "Minot", airport: "Minot International Airport" },
  {
    code: "GCC",
    name: "Gillette",
    airport: "Gillette-Campbell County Airport",
  },
  { code: "CDR", name: "Chadron", airport: "Chadron Municipal Airport" },
  {
    code: "LBF",
    name: "North Platte",
    airport: "North Platte Regional Airport",
  },
  {
    code: "BFF",
    name: "Scottsbluff",
    airport: "Western Nebraska Regional Airport",
  },
  { code: "SNY", name: "Sidney", airport: "Sidney Municipal Airport" },
  { code: "IMT", name: "Iron Mountain", airport: "Ford Airport" },
  {
    code: "EAU",
    name: "Eau Claire",
    airport: "Chippewa Valley Regional Airport",
  },
  {
    code: "RST",
    name: "Rochester",
    airport: "Rochester International Airport",
  },
  { code: "SPW", name: "Spencer", airport: "Spencer Municipal Airport" },
  { code: "MCW", name: "Mason City", airport: "Mason City Municipal Airport" },
  { code: "DBQ", name: "Dubuque", airport: "Dubuque Regional Airport" },
  { code: "FOD", name: "Fort Dodge", airport: "Fort Dodge Regional Airport" },
  { code: "ALO", name: "Waterloo", airport: "Waterloo Regional Airport" },
  { code: "SUX", name: "Sioux City", airport: "Sioux Gateway Airport" },
  { code: "HON", name: "Huron", airport: "Huron Regional Airport" },
  { code: "ABR", name: "Aberdeen", airport: "Aberdeen Regional Airport" },
  { code: "ATY", name: "Watertown", airport: "Watertown Regional Airport" },
  { code: "SGP", name: "Singapore", airport: "Changi Airport" },
  { code: "BKK", name: "Bangkok", airport: "Suvarnabhumi Airport" },
  {
    code: "KUL",
    name: "Kuala Lumpur",
    airport: "Kuala Lumpur International Airport",
  },
  { code: "HAN", name: "Hanoi", airport: "Noi Bai International Airport" },
  {
    code: "HKG",
    name: "Hong Kong",
    airport: "Hong Kong International Airport",
  },
  {
    code: "MNL",
    name: "Manila",
    airport: "Ninoy Aquino International Airport",
  },
  {
    code: "CGK",
    name: "Jakarta",
    airport: "Soekarno-Hatta International Airport",
  },
  {
    code: "BKI",
    name: "Kota Kinabalu",
    airport: "Kota Kinabalu International Airport",
  },
  {
    code: "DPS",
    name: "Denpasar",
    airport: "Ngurah Rai International Airport",
  },
  { code: "CEB", name: "Cebu", airport: "Mactan-Cebu International Airport" },
  { code: "PEN", name: "Penang", airport: "Penang International Airport" },
  {
    code: "REP",
    name: "Siem Reap",
    airport: "Siem Reap International Airport",
  },
  { code: "HKT", name: "Phuket", airport: "Phuket International Airport" },
  {
    code: "PNH",
    name: "Phnom Penh",
    airport: "Phnom Penh International Airport",
  },
  { code: "VTE", name: "Vientiane", airport: "Wattay International Airport" },
  { code: "RGN", name: "Yangon", airport: "Yangon International Airport" },
  { code: "SUB", name: "Surabaya", airport: "Juanda International Airport" },
  { code: "MFM", name: "Macau", airport: "Macau International Airport" },
  {
    code: "SGN",
    name: "Ho Chi Minh City",
    airport: "Tan Son Nhat International Airport",
  },
  {
    code: "CNX",
    name: "Chiang Mai",
    airport: "Chiang Mai International Airport",
  },
  { code: "DAD", name: "Da Nang", airport: "Da Nang International Airport" },
  { code: "KBV", name: "Krabi", airport: "Krabi International Airport" },
  { code: "USM", name: "Koh Samui", airport: "Samui International Airport" },
  {
    code: "LPQ",
    name: "Luang Prabang",
    airport: "Luang Prabang International Airport",
  },
  {
    code: "KMG",
    name: "Kunming",
    airport: "Kunming Changshui International Airport",
  },
  {
    code: "REP",
    name: "Siem Reap",
    airport: "Siem Reap International Airport",
  },
  { code: "MDL", name: "Mandalay", airport: "Mandalay International Airport" },
  {
    code: "DPS",
    name: "Denpasar",
    airport: "Ngurah Rai International Airport",
  },
  {
    code: "BTJ",
    name: "Banda Aceh",
    airport: "Sultan Iskandar Muda International Airport",
  },
  { code: "KNO", name: "Medan", airport: "Kuala Namu International Airport" },
  {
    code: "JOG",
    name: "Yogyakarta",
    airport: "Adisucipto International Airport",
  },
  {
    code: "DIL",
    name: "Dili",
    airport: "Presidente Nicolau Lobato International Airport",
  },
  {
    code: "PKU",
    name: "Pekanbaru",
    airport: "Sultan Syarif Kasim II International Airport",
  },
  {
    code: "BDO",
    name: "Bandung",
    airport: "Husein Sastranegara International Airport",
  },
  { code: "SUB", name: "Surabaya", airport: "Juanda International Airport" },
  {
    code: "UPG",
    name: "Makassar",
    airport: "Sultan Hasanuddin International Airport",
  },
  { code: "LOP", name: "Lombok", airport: "Lombok International Airport" },
  { code: "KOE", name: "Kupang", airport: "El Tari International Airport" },
  {
    code: "DPS",
    name: "Denpasar",
    airport: "Ngurah Rai International Airport",
  },
  { code: "PAR", name: "Paris", airport: "Charles de Gaulle Airport" },
  { code: "LON", name: "London", airport: "Heathrow Airport" },
  { code: "ROM", name: "Rome", airport: "Leonardo da Vinci–Fiumicino Airport" },
  { code: "BER", name: "Berlin", airport: "Berlin Brandenburg Airport" },
  {
    code: "MAD",
    name: "Madrid",
    airport: "Adolfo Suárez Madrid–Barajas Airport",
  },
  { code: "AMS", name: "Amsterdam", airport: "Amsterdam Airport Schiphol" },
  { code: "BCN", name: "Barcelona", airport: "Barcelona–El Prat Airport" },
  { code: "FRA", name: "Frankfurt", airport: "Frankfurt Airport" },
  { code: "MIL", name: "Milan", airport: "Milan Malpensa Airport" },
  { code: "MUC", name: "Munich", airport: "Munich Airport" },
  { code: "VIE", name: "Vienna", airport: "Vienna International Airport" },
  { code: "ZRH", name: "Zurich", airport: "Zurich Airport" },
  { code: "CPH", name: "Copenhagen", airport: "Copenhagen Airport" },
  { code: "OSL", name: "Oslo", airport: "Oslo Airport, Gardermoen" },
  { code: "HEL", name: "Helsinki", airport: "Helsinki-Vantaa Airport" },
  { code: "STO", name: "Stockholm", airport: "Stockholm Arlanda Airport" },
  { code: "BRU", name: "Brussels", airport: "Brussels Airport" },
  { code: "ATH", name: "Athens", airport: "Athens International Airport" },
  { code: "DUB", name: "Dublin", airport: "Dublin Airport" },
  { code: "EDI", name: "Edinburgh", airport: "Edinburgh Airport" },
  { code: "LIS", name: "Lisbon", airport: "Lisbon Airport" },
  { code: "PRG", name: "Prague", airport: "Václav Havel Airport Prague" },
  {
    code: "BUD",
    name: "Budapest",
    airport: "Budapest Ferenc Liszt International Airport",
  },
  { code: "WAR", name: "Warsaw", airport: "Warsaw Chopin Airport" },
  { code: "IST", name: "Istanbul", airport: "Istanbul Airport" },
  {
    code: "MOS",
    name: "Moscow",
    airport: "Sheremetyevo International Airport",
  },
  { code: "STP", name: "Saint Petersburg", airport: "Pulkovo Airport" },
  { code: "LIV", name: "Liverpool", airport: "Liverpool John Lennon Airport" },
  { code: "MAN", name: "Manchester", airport: "Manchester Airport" },
  { code: "GLA", name: "Glasgow", airport: "Glasgow Airport" },
  { code: "BHX", name: "Birmingham", airport: "Birmingham Airport" },
  { code: "HAM", name: "Hamburg", airport: "Hamburg Airport" },
  { code: "NCE", name: "Nice", airport: "Nice Côte d'Azur Airport" },
  { code: "ZAG", name: "Zagreb", airport: "Zagreb Airport" },
  { code: "LJU", name: "Ljubljana", airport: "Ljubljana Jože Pučnik Airport" },
  { code: "SKP", name: "Skopje", airport: "Skopje International Airport" },
  { code: "SOF", name: "Sofia", airport: "Sofia Airport" },
  { code: "BEG", name: "Belgrade", airport: "Belgrade Nikola Tesla Airport" },
  {
    code: "BUC",
    name: "Bucharest",
    airport: "Henri Coandă International Airport",
  },
  { code: "KIE", name: "Kiev", airport: "Boryspil International Airport" },
  { code: "PAR", name: "Paris", airport: "Charles de Gaulle Airport" },
  { code: "LON", name: "London", airport: "Heathrow Airport" },
  { code: "ROM", name: "Rome", airport: "Leonardo da Vinci–Fiumicino Airport" },
  { code: "BER", name: "Berlin", airport: "Berlin Brandenburg Airport" },
  {
    code: "MAD",
    name: "Madrid",
    airport: "Adolfo Suárez Madrid–Barajas Airport",
  },
  { code: "AMS", name: "Amsterdam", airport: "Amsterdam Airport Schiphol" },
  { code: "BCN", name: "Barcelona", airport: "Barcelona–El Prat Airport" },
  { code: "FRA", name: "Frankfurt", airport: "Frankfurt Airport" },
  { code: "MIL", name: "Milan", airport: "Milan Malpensa Airport" },
  { code: "MUC", name: "Munich", airport: "Munich Airport" },
  { code: "VIE", name: "Vienna", airport: "Vienna International Airport" },
  { code: "ZRH", name: "Zurich", airport: "Zurich Airport" },
  { code: "CPH", name: "Copenhagen", airport: "Copenhagen Airport" },
  { code: "OSL", name: "Oslo", airport: "Oslo Airport, Gardermoen" },
  { code: "HEL", name: "Helsinki", airport: "Helsinki-Vantaa Airport" },
  { code: "STO", name: "Stockholm", airport: "Stockholm Arlanda Airport" },
  { code: "BRU", name: "Brussels", airport: "Brussels Airport" },
  { code: "ATH", name: "Athens", airport: "Athens International Airport" },
  { code: "DUB", name: "Dublin", airport: "Dublin Airport" },
  { code: "EDI", name: "Edinburgh", airport: "Edinburgh Airport" },
  { code: "LIS", name: "Lisbon", airport: "Lisbon Airport" },
  { code: "PRG", name: "Prague", airport: "Václav Havel Airport Prague" },
  {
    code: "BUD",
    name: "Budapest",
    airport: "Budapest Ferenc Liszt International Airport",
  },
  { code: "WAR", name: "Warsaw", airport: "Warsaw Chopin Airport" },
  { code: "IST", name: "Istanbul", airport: "Istanbul Airport" },
  {
    code: "MOS",
    name: "Moscow",
    airport: "Sheremetyevo International Airport",
  },
  { code: "STP", name: "Saint Petersburg", airport: "Pulkovo Airport" },
  { code: "LIV", name: "Liverpool", airport: "Liverpool John Lennon Airport" },
  { code: "MAN", name: "Manchester", airport: "Manchester Airport" },
  { code: "GLA", name: "Glasgow", airport: "Glasgow Airport" },
  { code: "BHX", name: "Birmingham", airport: "Birmingham Airport" },
  { code: "HAM", name: "Hamburg", airport: "Hamburg Airport" },
  { code: "NCE", name: "Nice", airport: "Nice Côte d'Azur Airport" },
  { code: "ZAG", name: "Zagreb", airport: "Zagreb Airport" },
  { code: "LJU", name: "Ljubljana", airport: "Ljubljana Jože Pučnik Airport" },
  { code: "SKP", name: "Skopje", airport: "Skopje International Airport" },
  { code: "SOF", name: "Sofia", airport: "Sofia Airport" },
  { code: "BEG", name: "Belgrade", airport: "Belgrade Nikola Tesla Airport" },
  {
    code: "BUC",
    name: "Bucharest",
    airport: "Henri Coandă International Airport",
  },
  { code: "KIE", name: "Kiev", airport: "Boryspil International Airport" },
  {
    code: "DEL",
    name: "Delhi",
    airport: "Indira Gandhi International Airport",
  },
  { code: "DXB", name: "Dubai", airport: "Dubai International Airport" },
  {
    code: "JED",
    name: "Jeddah",
    airport: "King Abdulaziz International Airport",
  },
  {
    code: "BOM",
    name: "Mumbai",
    airport: "Chhatrapati Shivaji Maharaj International Airport",
  },
  {
    code: "ISB",
    name: "Islamabad",
    airport: "Islamabad International Airport",
  },
  { code: "DOH", name: "Doha", airport: "Hamad International Airport" },
  { code: "KHI", name: "Karachi", airport: "Jinnah International Airport" },
  {
    code: "AUH",
    name: "Abu Dhabi",
    airport: "Abu Dhabi International Airport",
  },
  { code: "DAC", name: "Dhaka", airport: "Shahjalal International Airport" },
  {
    code: "Riyadh",
    name: "Riyadh",
    airport: "King Khalid International Airport",
  },
  {
    code: "CMB",
    name: "Colombo",
    airport: "Bandaranaike International Airport",
  },
  { code: "MCT", name: "Muscat", airport: "Muscat International Airport" },
  {
    code: "LHE",
    name: "Lahore",
    airport: "Allama Iqbal International Airport",
  },
  { code: "KWI", name: "Kuwait City", airport: "Kuwait International Airport" },
  { code: "Bahrain", name: "Manama", airport: "Bahrain International Airport" },
  {
    code: "CCU",
    name: "Kolkata",
    airport: "Netaji Subhas Chandra Bose International Airport",
  },
  { code: "KBL", name: "Kabul", airport: "Hamid Karzai International Airport" },
  { code: "MAA", name: "Chennai", airport: "Chennai International Airport" },
  {
    code: "BLR",
    name: "Bengaluru",
    airport: "Kempegowda International Airport",
  },
  { code: "JAI", name: "Jaipur", airport: "Jaipur International Airport" },
  {
    code: "TRV",
    name: "Thiruvananthapuram",
    airport: "Trivandrum International Airport",
  },
  { code: "HRG", name: "Hurghada", airport: "Hurghada International Airport" },
  {
    code: "AMD",
    name: "Ahmedabad",
    airport: "Sardar Vallabhbhai Patel International Airport",
  },
  { code: "SHJ", name: "Sharjah", airport: "Sharjah International Airport" },
  {
    code: "KTM",
    name: "Kathmandu",
    airport: "Tribhuvan International Airport",
  },
  { code: "SIN", name: "Singapore", airport: "Changi Airport" },
  { code: "MLE", name: "Malé", airport: "Velana International Airport" },
  { code: "DMM", name: "Dammam", airport: "King Fahd International Airport" },
  {
    code: "DPS",
    name: "Denpasar",
    airport: "Ngurah Rai International Airport",
  },
  { code: "GOI", name: "Goa", airport: "Goa International Airport" },
  { code: "DAC", name: "Dhaka", airport: "Shahjalal International Airport" },
  { code: "COK", name: "Kochi", airport: "Cochin International Airport" },
  { code: "KHI", name: "Karachi", airport: "Jinnah International Airport" },
  { code: "AMM", name: "Amman", airport: "Queen Alia International Airport" },
  { code: "DOH", name: "Doha", airport: "Hamad International Airport" },
  { code: "BAH", name: "Bahrain", airport: "Bahrain International Airport" },
  { code: "MCT", name: "Muscat", airport: "Muscat International Airport" },
  { code: "TLV", name: "Tel Aviv", airport: "Ben Gurion Airport" },
  {
    code: "BEY",
    name: "Beirut",
    airport: "Beirut-Rafic Hariri International Airport",
  },
];
